RatedTravel App/RatedTravel.Web/Controllers/BarController.cs
using Microsoft.AspNetCore.Mvc;
using RatedTravel.Core.Interfaces;
using RatedTravel.Core.Services;
using RatedTravel.Common;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using RatedTravel.Web.ViewModels.Bar;
using RatedTravel.Data.DataModels;
using System.Threading.Tasks;
using System.IO;
using System;
using System.Collections.Generic;

namespace RatedTravel.App.Web.Controllers
{
    [Authorize]
    public class BarController : Controller
    {
        private readonly IEmployeeService employeeService;
        private readonly ICityService cityService;
        private readonly IBarService barService;
        private readonly UserManager<ApplicationUser> userManager;

        public BarController(IEmployeeService employeeService, ICityService cityService, IBarService barService, UserManager<ApplicationUser> userManager)
        {
            this.cityService = cityService;
            this.employeeService = employeeService;
            this.barService = barService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> AddBar()
        {
            var user = await userManager.GetUserAsync(User);
            bool isUser = user != null;

            if (!isUser)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You have to be logged in to add a bar!";
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBar(BarFormModel model)
        {
            var user = await userManager.GetUserAsync(User);
            bool isUser = user != null;

            bool doesBarExistByName = await barService.DoesBarExistsByName(model.Name);

            if (doesBarExistByName)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "The bar already exists. To add more bars of the same chain, edit the existing bar and add the address of the new locations.";
                return RedirectToAction("Index", "Home");
            }

            if (!isUser)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You have to be logged in to add a bar!";
                return RedirectToAction("Index", "Home");
            }

            bool doesCityExists = await this.cityService.DoesCityExistsAsync(model.CityName);

            if (!doesCityExists)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "This city does not exist! Try another one.";
            }

            try
            {
                // Handle the uploaded image file
                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    // Generate the filename for the image using the bar name
                    var fileName = model.Name + "_" + model.ImageFile.FileName;

                    // Define the file path within the wwwroot folder where the image will be saved
                    var filePath = Path.Combine("wwwroot", "images", fileName);

                    // Save the image file to the specified path
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await model.ImageFile.CopyToAsync(fileStream);
                    }

                    await barService.CreateBarAsync(user.Id.ToString(), model);
                }
            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Are you sure you are logged in?";
                return this.RedirectToAction("Index", "Home");
            }

            //TODO: to return to ALL bars.
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllBarsInACity(string cityId)
        {
            List<BarAllModel> allBarsInACity = new List<BarAllModel>();

            try
            {
                allBarsInACity.AddRange(await barService.AllBarsInACityAsync(cityId));

                if (allBarsInACity.Count == 0)
                {
                    ModelState.AddModelError("", "No bars found in the selected city.");
                }

                if (!ModelState.IsValid)
                {
                    this.TempData[NotificationMessagesConstants.ErrorMessage] = "We couldn't find bars in this city.";

                    // Get the previous URL from Referer header
                    string previousUrl = Request.Headers["Referer"].ToString();
                    return Redirect(previousUrl);
                }

                return View(allBarsInACity);
            }
            catch (Exception)
            {

                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";

                // Get the previous URL from Referer header
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> BarDetails(string cityId, string barId)
        {
            try
            {
                var bar = await barService.DetailsAsync(cityId, barId);

                if (bar == null)
                {
                    ModelState.AddModelError("", "Bar not found");
                    this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";
                    return this.RedirectToAction("Index", "Home");
                }

                return View(bar);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Oops, something went wrong :( Please try again later or contact us");
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";
                return this.RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SubmitReview(string barId, BarRateAndReviewModel model)
        {
            bool doesBarExistsByName = await barService.DoesBarExistsByIdAsync(model.BarId);

            if (!doesBarExistsByName)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You cannot write a review for this bar - please contact the administrators.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {
                await barService.SendReviewAsync(barId, model);
                this.TempData[NotificationMessagesConstants.SuccessMessage] = "Thank you for your review!";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :(";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReview(string? reviewId)
        {
            if (string.IsNullOrEmpty(reviewId))
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Invalid reviewId.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {
                await barService.DeleteReviewByIdAsync(reviewId);
                this.TempData[NotificationMessagesConstants.SuccessMessage] = "Review deleted successfully!";

                string previousUrl = Request.Headers["Referer"].ToString();

                // Get the URL of the page before the previous one
                string pageBeforePreviousUrl = Request.Headers["Referer"];

                // Redirect to the page before the previous one
                if (!string.IsNullOrEmpty(pageBeforePreviousUrl))
                {
                    return Redirect(pageBeforePreviousUrl);
                }
                else
                {
                    // If there's no page before the previous one, redirect to a default URL
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :(";
                string previousUrl = Request.Headers["Referer"].ToString();
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBar(string barId)
        {
            if (string.IsNullOrEmpty(barId))
            {
                TempData[NotificationMessagesConstants.ErrorMessage] = "Invalid barId.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {
                BarDeleteModel deleteModel = await barService.GetBarForDeleteAsync(barId);

                return View(deleteModel);
            }
            catch (Exception)
            {
                TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :(";
                return RedirectToAction("Index", "Home");

RatedTravel App/RatedTravel.Web/Views/City/AddCity.cshtml
@model CityFormModel

@{
	ViewData["Title"] = "Add City";
}
      


<div class="container-fluid bg-lightblue-transparent text-white py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card darkblue text-white border-4">
                <div class="card-header bg-secondary text-white">
                    <h3 class="mb-0">Add a City</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="City" asp-action="AddCity" enctype="multipart/form-data">
                        <div class="form-group">
                            <label asp-for="@Model.Name" class="text-black">City Name:</label>
                            <input asp-for="@Model.Name" class="form-control bg-lightblue text-black" id="Name" name="Name" required>
                            <span asp-validation-for="Name" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Country" class="text-black">Country:</label>
                            <input asp-for="Country" class="form-control bg-lightblue text-black" id="Country" name="Country" required>
                            <span asp-validation-for="Country" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ImageFile" class="text-black">Upload Image:</label>
                            <div class="input-group">
                                <input asp-for="ImageFile" class="form-control-file bg-lightblue text-black" id="ImageFile" name="ImageFile">
                            </div>
                            <span asp-validation-for="ImageFile" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="text-black">Description:</label>
                            <textarea asp-for="Description" class="form-control bg-lightblue text-black" id="Description" name="Description" rows="3" required></textarea>
                            <span asp-validation-for="Description" class="small text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="NightlifeScore" class="text-black">Night Life Score (1-5):</label>
                            <input asp-for="NightlifeScore" class="form-control bg-lightblue text-black" id="NightlifeScore" name="NightlifeScore" min="1" max="5" required>
                            <span asp-validation-for="NightlifeScore" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TransportScore" class="text-black">Transportation Score (1-5):</label>
                            <input asp-for="TransportScore" class="form-control bg-lightblue text-black" id="TransportScore" name="TransportScore" min="1" max="5" required>
                            <span asp-validation-for="TransportScore" class="small text-danger"></span>
                        </div>

                        <button class="btn card-header bg-secondary text-white border">Add City</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml" />
}

RatedTravel App/RatedTravel.Web/Views/City/AllCities.cshtml
@using RatedTravel.Core.Interfaces
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model List<CityAllModel>

@inject IEmployeeService EmployeeService

@{
    string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    bool isEmployee = await this.EmployeeService.EmployeeExistsByUserIdAsync(userId);
    ViewData["Title"] = "Cities";

    bool isAdmin = User.IsInRole(AdminRoleName);
}

<div class="container-fluid bg-lightblue-transparent text-white py-5">
    @foreach (var city in Model)
    {
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                <div class="card darkblue text-white border-4">
                    <div class="card-header bg-secondary text-white">
                        <h3 class="mb-0">@city.Name</h3>
                    </div>
                    <div class="card-body text-black">
                        <div class="container">
                            <div class="row">
                                <div class="col text-center">
                                    <img class="card-img-top" style="max-height: 300px;" src="~/Images/@city.ImageUrl" alt="City Image">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col text-center">
                                    <p>Located in: <b>@city.Country</b></p>
                                    <p>@city.Description</p>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col text-left">
                                    <p>
                                        Nightlife Score
                                        <div class="starability-result" data-rating="@city.NightlifeScore"></div>
                                    </p>
                                </div>
                                <div class="col text-right">
                                    <p>
                                        Transportation Score
                                        <div class="starability-result" data-rating="@city.TransportScore"></div>
                                    </p>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col text-center">
                                    @if (isEmployee == true)
                                    {
                                        <a class="btn btn-warning" asp-controller="City" asp-action="EditCity" asp-route-id="@city.Id">Edit</a>
                                        
                                    }
                                    @if (isAdmin == true)
									{
                                        <a class="ml-2 btn btn-danger" asp-controller="City" asp-action="DeleteCity" asp-route-id="@city.Id">Delete</a>
									}


                                    <a class="btn card-header bg-secondary text-white border" asp-controller="Home" asp-action="Index">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<style>
    .score-number {
        font-size: 18px;
        font-weight: bold;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('.starability-result').starability();
    });
</script>

RatedTravel App/RatedTravel.Web/Views/City/DeleteCity.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using RatedTravel.Core.Interfaces
@model CityDeleteModel

@inject IEmployeeService EmployeeService

@{
	bool isAdmin = User.IsInRole(AdminRoleName);
}

@{
    ViewData["Title"] = "Delete City";
}

<div class="container-fluid bg-lightblue-transparent text-white py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card darkblue text-white border-4">
                <div class="card-header bg-secondary text-white">
                    <h3 class="mb-0">@Model.Name</h3>
                </div>
                <div class="card-body text-black">
                    <div class="container">
                        <div class="row">
                            <div class="col text-center">
                                <img class="card-img-top" style="max-height: 300px;" src="~/Images/@Model.ImageUrl" alt="City Image">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col text-center">
                                <p>Located in: <b>@Model.Country</b></p>
                            </div>
                        </div>

	                    <div class="row mt-3">
                            <div class="col text-center">
                                @if (isAdmin == true)
                                {
	                                <form method="post" asp-controller="City" asp-action="DeleteCity">
		                                <input type="hidden" asp-for="Id" />
		                                <button type="submit" class="ml-2 btn btn-danger">Delete</button>
	                                </form>
	                                <hr>
	                                <a href="javascript:history.go(-1)"  class="btn card-header bg-secondary text-white border">Cancel</a>
	                                
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

RatedTravel App/RatedTravel.Web/Views/City/EditCity.cshtml
@model CityFormModel

<div class="container-fluid bg-lightblue-transparent text-white py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card darkblue text-white border-4">
                <div class="card-header bg-secondary text-white">
                    <h3 class="mb-0">Edit City</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="City" asp-action="EditCity" enctype="multipart/form-data">
                        <div class="form-group">
                            <label asp-for="@Model.Name" class="text-black">City Name:</label>
                            <input asp-for="@Model.Name" class="form-control bg-lightblue text-black" id="Name" name="Name" required>
                            <span asp-validation-for="Name" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Country" class="text-black">Country:</label>
                            <input asp-for="Country" class="form-control bg-lightblue text-black" id="Country" name="Country" required>
                            <span asp-validation-for="Country" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ImageFile" class="text-black">Upload Image:</label>
                            <div class="input-group">
                                <input asp-for="ImageFile" class="form-control-file bg-lightblue text-black" id="ImageFile" name="ImageFile">
                            </div>
                            <span asp-validation-for="ImageFile" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="text-black">Description:</label>
                            <textarea asp-for="Description" class="form-control bg-lightblue text-black" id="Description" name="Description" rows="3" required></textarea>
                            <span asp-validation-for="Description" class="small text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="NightlifeScore" class="text-black">Night Life Score (1-5):</label>
                            <input asp-for="NightlifeScore" class="form-control bg-lightblue text-black" id="NightlifeScore" name="NightlifeScore" min="1" max="5" required>
                            <span asp-validation-for="NightlifeScore" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TransportScore" class="text-black">Transportation Score (1-5):</label>
                            <input asp-for="TransportScore" class="form-control bg-lightblue text-black" id="TransportScore" name="TransportScore" min="1" max="5" required>
                            <span asp-validation-for="TransportScore" class="small text-danger"></span>
                        </div>
                        <hr />
                        <button class="ml-2 btn btn-warning">Edit City</button>
                        <hr>
                        <a href="javascript:history.go(-1)" class="btn card-header bg-secondary text-white border">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
	<partial name="_ValidationScriptsPartial.cshtml" />
}

RatedTravel App/RatedTravel.Web/Views/City/SelectCity.cshtml
@using RatedTravel.Core.Interfaces
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CitySelectModel

@inject IEmployeeService EmployeeService

@{
	string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
	bool isEmployee =
        await this.EmployeeService.EmployeeExistsByUserIdAsync(userId);
	bool isAdmin = User.IsInRole(AdminRoleName);
}

@{
    ViewData["Title"] = "Welcome to " + Model.Name;
}
<div class="container-fluid bg-lightblue-transparent text-white py-5">
	<div class="row justify-content-center align-items-center">
		<div class="col-md-8">
			<div class="card darkblue text-white border-4">
				<div class="card-header bg-secondary text-white">
					<h3 class="mb-0">@Model.Name</h3>
				</div>
				<div class="card-body text-black">
					<div class="container">
						<div class="row">
							<div class="col text-center">
								<img class="card-img-top" style="max-height: 300px;" src="~/Images/@Model.ImageUrl" alt="City Image">
							</div>
						</div>
						<div class="row mt-3">
							<div class="col text-center">
								<p>Located in: <b>@Model.Country</b></p>
								<p>@Model.Description</p>
							</div>
						</div>
						<div class="row mt-3">
							<div class="col text-left">
								<p>
									Nightlife Score
									<div class="starability-result" data-rating="@Model.NightlifeScore"></div>
								</p>
							</div>
							<div class="col text-right">
								<p>
									Transportation Score
									<div class="starability-result" data-rating="@Model.TransportScore"></div>
								</p>
							</div>
						</div>
						<hr> 
						<div class="row mt-3 justify-content-center">
							<div class="col text-center">
								<a class="btn card-header bg-secondary text-white border" asp-controller="Restaurant" asp-action="AllRestaurantsInACity" asp-route-cityId="@Model.Id">View all restaurants in @Model.Name</a>

							</div>
							<div class="col text-center">
								<a class="btn card-header bg-secondary text-white border" asp-controller="Bar" asp-action="AllBarsInACity" asp-route-cityId="@Model.Id">View all bars in @Model.Name</a>
							</div>
						</div>
						<hr> 
						<div class="row mt-3">
							<div class="col text-center">
								@if (isEmployee == true)
								{
									<a class="btn btn-warning" asp-controller="City" asp-action="EditCity" asp-route-id="@Model.Id">Edit</a>
								}
								@if (isAdmin == true)
								{
									<a class="ml-2 btn btn-danger" asp-controller="City" asp-action="DeleteCity" asp-route-id="@Model.Id">Delete</a>
								}
								<a class="btn card-header bg-secondary text-white border" asp-controller="Home" asp-action="Index">Back</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




<style>
    .score-number {
        font-size: 18px;
        font-weight: bold;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
    $(document).ready(function () {
        $('.starability-result').starability();
    });
</script>