RatedTravel App/RatedTravel.Web/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RatedTravel.Core.Interfaces;
using RatedTravel.Data.DataModels;
using RatedTravel.Web.ViewModels.Restaurant;
using RatedTravel.Common;
using System.Security.Claims;

namespace RatedTravel.App.Web.Controllers
{
    [Authorize]
    public class RestaurantController : Controller
    {
        private readonly IEmployeeService employeeService;
        private readonly ICityService cityService;
        private readonly IRestaurantService restaurantService;
        private readonly UserManager<ApplicationUser> userManager;


        public RestaurantController(IEmployeeService employeeService, ICityService cityService, IRestaurantService restaurantService, UserManager<ApplicationUser> userManager)
        {
            this.cityService = cityService;
            this.employeeService = employeeService;
            this.restaurantService = restaurantService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> AddRestaurant()
        {
            var user = await userManager.GetUserAsync(User);
            bool isUser = user != null;

            if (!isUser)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You have to logged in in order to add a restaurant!";
                return  RedirectToAction("Index", "Home");
            }


            return View();
        }

        [HttpPost]

        public async Task<IActionResult> AddRestaurant(RestaurantFormModel model)
        {
            
            var user = await userManager.GetUserAsync(User);
            bool isUser = user != null;

            bool doesRestaurantExistByName = await restaurantService.DoesRestaurantExistsByName(model.Name);

            if (doesRestaurantExistByName)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "The restaurant already exists. To add more restaurants of the same chain edit the existing restaurant and add the address of the new locations.";
                return RedirectToAction("Index", "Home");
            }

            if (!isUser)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You have to logged in in order to add a restaurant!";
                return RedirectToAction("Index", "Home");
            }
            bool doesCityExists = await this.cityService.DoesCityExistsAsync(model.CityName);

            if (!doesCityExists)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "This city does not exists! Try another one.";
            }

            try
            {
                // Handle the uploaded image file
                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    // Generate the filename for the image using the city name
                    var fileName = model.Name + "_" + model.ImageFile.FileName;

                    // Define the file path within the wwwroot folder where the image will be saved
                    var filePath = Path.Combine("wwwroot", "images", fileName);

                    // Save the image file to the specified path
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await model.ImageFile.CopyToAsync(fileStream);
                    }

                    await restaurantService.CreateRestaurantAsync(user.Id.ToString(), model);
                }

            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Are you sure you are logged in?";
                return this.RedirectToAction("Index", "Home");
            }



            //TODO: to return to ALL restaurants. 
            return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllRestaurantsInACity(string cityId)
        {
            List<RestaurantAllModel> allRestaurantsInACity = new List<RestaurantAllModel>();

            try
            {
                allRestaurantsInACity.AddRange(await restaurantService.AllRestaurantsInACityAsync(cityId));

                if (allRestaurantsInACity.Count == 0)
                {
                    ModelState.AddModelError("", "No restaurants found in the selected city.");
                }

                if (!ModelState.IsValid)
                {
                    this.TempData[NotificationMessagesConstants.ErrorMessage] = "We couldn't find restaurants in this city.";

                    // Get the previous URL from Referer header
                    string previousUrl = Request.Headers["Referer"].ToString();
                    return Redirect(previousUrl);
                }

                return View(allRestaurantsInACity);
            }
            catch (Exception ex)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";

                // Get the previous URL from Referer header
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }
        }



        [HttpGet]
		[AllowAnonymous]

        public async Task<IActionResult> RestaurantDetails(string cityId, string restaurantId)
        {
            try
            {
                var restaurant = await restaurantService.DetailsAsync(cityId, restaurantId);

                if (restaurant == null)
                {
                    ModelState.AddModelError("", "Restaurant not found");
                    this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";
                    return this.RedirectToAction("Index", "Home");
                }

                return View(restaurant);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Oops, something went wrong :( Please try again later or contact us");
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :( Please try again later or contact us";
                return this.RedirectToAction("Index", "Home");
            }
        }




        [HttpPost]
        [AllowAnonymous]

        public async Task<IActionResult> SubmitReview(string restaurantId, RestaurantRateAndReviewModel model)
        {
            bool doesRestaurantExistsByName = await restaurantService.DoesRestaurantExistsByIdAsync(model.RestaurantId);

            if (!doesRestaurantExistsByName)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] =
                    "You cannot write a review for this restaurant - please contact the administrators.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {
                await restaurantService.SendReviewAsync(restaurantId, model);
                this.TempData[NotificationMessagesConstants.SuccessMessage] = "Thank you for your review!";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :(";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReview(string? reviewId)
        {
            if (string.IsNullOrEmpty(reviewId))
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Invalid reviewId.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {
                await restaurantService.DeleteReviewByIdAsync(reviewId);
                this.TempData[NotificationMessagesConstants.SuccessMessage] = "Review deleted successfully!";


                string previousUrl = Request.Headers["Referer"].ToString();

                // Get the URL of the page before the previous one
                string pageBeforePreviousUrl = Request.Headers["Referer"];

                // Redirect to the page before the previous one
                if (!string.IsNullOrEmpty(pageBeforePreviousUrl))
                {
                    return Redirect(pageBeforePreviousUrl);
                }
                else
                {
                    // If there's no page before the previous one, redirect to a default URL
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                this.TempData[NotificationMessagesConstants.ErrorMessage] = "Oops, something went wrong :(";
                string previousUrl = Request.Headers["Referer"].ToString();
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRestaurant(string restaurantId)
        {
            if (string.IsNullOrEmpty(restaurantId))
            {
                TempData[NotificationMessagesConstants.ErrorMessage] = "Invalid restaurantId.";
                string previousUrl = Request.Headers["Referer"].ToString();
                return Redirect(previousUrl);
            }

            try
            {

RatedTravel App/RatedTravel.Web/Views/Restaurant/AddRestaurant.cshtml
@model RatedTravel.Web.ViewModels.Restaurant.RestaurantFormModel

@{
    ViewData["Title"] = "Add Restaurant";
}

<div class="container-fluid bg-lightblue-transparent text-white py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card darkblue text-white border-4">
                <div class="card-header bg-secondary text-white">
                    <h3 class="mb-0">Add a Restaurant</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Restaurant" asp-action="AddRestaurant" enctype="multipart/form-data">
	                    <div class="form-group">
		                    <label asp-for="@Model.Name" class="text-black">Restaurant Name:</label>
		                    <input asp-for="@Model.Name" class="form-control bg-lightblue text-black" id="Name" name="Name" required>
		                    <span asp-validation-for="Name" class="small text-danger"></span>
	                    </div>
	                    <div class="form-group">
		                    <label asp-for="@Model.CityName" class="text-black">City Name:</label>
                            <input asp-for="@Model.CityName" class="form-control bg-lightblue text-black" id="CityName" name="CityName" required>
                            <span asp-validation-for="CityName" class="small text-danger"></span>
	                    </div>
                        <div class="form-group">
                            <label asp-for="ImageFile" class="text-black">Upload Image:</label>
                            <div class="input-group">
                                <input asp-for="ImageFile" class="form-control-file bg-lightblue text-black" id="ImageFile" name="ImageFile">
                            </div>
                            <span asp-validation-for="ImageFile" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="text-black">Address:</label>
                            <input asp-for="Address" class="form-control bg-lightblue text-black" id="Address" name="Address" required>
                            <span asp-validation-for="Address" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="text-black">Description:</label>
                            <textarea asp-for="Description" class="form-control bg-lightblue text-black" id="Description" name="Description" rows="3" required></textarea>
                            <span asp-validation-for="Description" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="OverallScore" class="text-black">Overall Score:</label>
                            <input asp-for="OverallScore" class="form-control bg-lightblue text-black" id="OverallScore" name="OverallScore" min="1" max="5" required>
                            <span asp-validation-for="OverallScore" class="small text-danger"></span>
                        </div>
                        <button class="btn card-header bg-secondary text-white border">Add Restaurant</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml" />
}

RatedTravel App/RatedTravel.Web/Views/Restaurant/AllRestaurants.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using RatedTravel.Core.Interfaces
@model List<RatedTravel.Web.ViewModels.Restaurant.RestaurantAllModel>

@{
    ViewData["Title"] = "All Restaurants in All cities";
}


@inject IEmployeeService EmployeeService

@{
    string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    bool isEmployee =
        await this.EmployeeService.EmployeeExistsByUserIdAsync(userId);
}

<style>
    .city-name-box {
        background-color: #f8f9fa;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 8px;
        text-align: center;
    }

    .rating-stars {
        color: #ffc107;
        font-size: 24px;
    }

    .rating-empty-stars {
        color: #ced4da;
        font-size: 24px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="city-name-box">
                <h3>Restaurants in All Cities</h3>
            </div>
        </div>
    </div>
    <div class="row">
        @foreach (var restaurant in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img class="card-img-top" style="max-height: 300px;" src="~/Images/@restaurant.Image" alt="City Image">
                    <div class="card-body">
                        <h5 class="card-title">@restaurant.Name</h5>
                        <p class="card-text">@restaurant.CityName</p>
                        <p class="card-text">@restaurant.Description</p>
                        <p class="card-text">Address: @restaurant.Address</p>
                        @if (restaurant.OverallScore > 0)
                        {
                            <div class="rating-stars">
                                @for (int i = 0; i < 5; i++)
                                {
                                    if (i < (int)restaurant.OverallScore)
                                    {
                                        <span class="bi bi-star-fill"></span>
                                    }
                                    else if (i == (int)restaurant.OverallScore && restaurant.OverallScore % 1 != 0)
                                    {
                                        <span class="bi bi-star-half"></span>
                                    }
                                    else
                                    {

                                        <span class="bi bi-star"></span>
                                    }
                                }
                            </div>
                        }
                        else
                        {
                            <p class="card-text">No reviews</p>
                        }
                        <p> Click on the details to see the reviews and to rate this place</p>
                        @* When the button is clicked, it navigates the user to the RestaurantDetails action in the Restaurant controller,
                    while passing the cityId and restaurantId as query parameters. *@
                        <a href="@Url.Action("RestaurantDetails", "Restaurant", new { cityId = restaurant.CityId, restaurantId = restaurant.Id })" class="btn btn-primary">Details</a>
                        @if (isEmployee)
                        {
                            <hr />
                            <form method="get" asp-controller="Restaurant" asp-action="EditRestaurant">
                                <input type="hidden" name="cityId" value="@restaurant.CityId" />
                                <input type="hidden" name="restaurantId" value="@restaurant.Id" />
                                <button type="submit" class="ml-2 btn btn-warning">Edit</button>
                            </form>
                            <hr />
                            <form method="get" asp-controller="Restaurant" asp-action="DeleteRestaurant">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="restaurantId" value="@restaurant.Id" />
                                <button type="submit" class="ml-2 btn btn-danger">Delete</button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

@section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml" />
}

RatedTravel App/RatedTravel.Web/Views/Restaurant/AllRestaurantsInACity.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using RatedTravel.Core.Interfaces
@model List<RatedTravel.Web.ViewModels.Restaurant.RestaurantAllModel>

@{
    ViewData["Title"] = "All Restaurants in " + Model[0].CityName;
}


@inject IEmployeeService EmployeeService

@{
	string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
	bool isEmployee =
		await this.EmployeeService.EmployeeExistsByUserIdAsync(userId);
}

<style>
    .city-name-box {
        background-color: #f8f9fa;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 8px;
        text-align: center;
    }

    .rating-stars {
        color: #ffc107;
        font-size: 24px;
    }

    .rating-empty-stars {
        color: #ced4da;
        font-size: 24px;
    }
</style>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="city-name-box d-flex align-items-center">
				<h3 class="flex-grow-1">Restaurants in @Model[0].CityName</h3>
				<a href="javascript:history.go(-1)" class="btn card-header bg-secondary text-white border">Back</a>
			</div>
			<hr>
		</div>
	</div>
    <div class="row">
        @foreach (var restaurant in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img class="card-img-top" style="max-height: 300px;" src="~/Images/@restaurant.Image" alt="City Image">
                    <div class="card-body">
                        <h5 class="card-title">@restaurant.Name</h5>
                        <p class="card-text">@restaurant.Description</p>
                        <p class="card-text">Address: @restaurant.Address</p>
                        @if (restaurant.OverallScore > 0)
                        {
                            <div class="rating-stars">
                                @for (int i = 0; i < 5; i++)
                                {
                                    if (i < (int)restaurant.OverallScore)
                                    {
                                        <span class="bi bi-star-fill"></span>
                                    }
                                    else if (i == (int)restaurant.OverallScore && restaurant.OverallScore % 1 != 0)
                                    {
                                        <span class="bi bi-star-half"></span>
                                    }
                                    else
                                    {
                                        
                                        <span class="bi bi-star"></span>
                                    }
                                }
                            </div>
                        }
                        else
                        {
                            <p class="card-text">No reviews</p>
                        }
                        <p> Click on the details to see the reviews and to rate this place</p>
                        @*When the button is clicked, it navigates the user to the RestaurantDetails action in the Restaurant controller,
                            while passing the cityId and restaurantId as query parameters.
*@                        <a href="@Url.Action("RestaurantDetails", "Restaurant", new { cityId = restaurant.CityId, restaurantId = restaurant.Id })" class="btn btn-primary">Details</a>
                        @if (isEmployee)
                        {
	                        <hr />
	                        <form method="get" asp-controller="Restaurant" asp-action="EditRestaurant">
		                        <input type="hidden" name="cityId" value="@restaurant.CityId" />
		                        <input type="hidden" name="restaurantId" value="@restaurant.Id" />
		                        <button type="submit" class="ml-2 btn btn-warning">Edit</button>
	                        </form>
	                        <hr />  
	                        <form method="get" asp-controller="Restaurant" asp-action="DeleteRestaurant">
		                        @Html.AntiForgeryToken()
                                <input type="hidden" name="restaurantId" value="@restaurant.Id" />
		                        <button type="submit" class="ml-2 btn btn-danger">Delete</button>
	                        </form>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

@section Scripts{
	<partial name="_ValidationScriptsPartial.cshtml" />
}

RatedTravel App/RatedTravel.Web/Views/Restaurant/DeleteRestaurant.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using RatedTravel.Core.Interfaces
@model RestaurantDeleteModel

@inject IEmployeeService EmployeeService

@{
    string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    bool isEmployee = await EmployeeService.EmployeeExistsByUserIdAsync(userId);
}

@{
    ViewData["Title"] = "Delete Restaurant";
}

<div class="container-fluid bg-lightblue-transparent text-white py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card darkblue text-white border-4">
                <div class="card-header bg-secondary text-white">
                    <h3 class="mb-0"> Restaurant: @Model.Name</h3>
                </div>
                <div class="card-body text-black">
                    <div class="container">
                        <div class="row">
                            <div class="col text-center">
                                <img class="card-img-top" style="max-height: 300px;" src="~/Images/@Model.ImageUrl" alt="Restaurant Image">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col text-center">
                                <p>Located in: <b>@Model.City</b></p>
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="col text-center">
                                @if (isEmployee)
                                {
	                                <form method="post" asp-controller="Restaurant" asp-action="DeleteRestaurant">
		                                <input type="hidden" asp-for="@Model.Id" />
		                                <button type="submit" class="ml-2 btn btn-danger">Delete</button>
	                                </form>
                                   @* Go back*@
                                    <hr>
                                    <a href="javascript:history.go(-1)"  class="btn card-header bg-secondary text-white border">Cancel</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

RatedTravel App/RatedTravel.Web/Views/Restaurant/EditRestaurant.cshtml
@model RestaurantFormModel



<<div class="container-fluid bg-lightblue-transparent text-white py-5">
	<div class="row justify-content-center align-items-center">
		<div class="col-md-6">
			<div class="card darkblue text-white border-4">
				<div class="card-header bg-secondary text-white">
					<h3 class="mb-0">Edit City</h3>
				</div>
				<div class="card-body">
                    <form asp-controller="Restaurant" asp-action="EditRestaurant" enctype="multipart/form-data">
                        <div class="form-group">
                            <label asp-for="Name" class="text-black">Restaurant Name:</label>
                            <input asp-for="Name" class="form-control bg-lightblue text-black" required>
                            <span asp-validation-for="Name" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CityName" class="text-black">City Name:</label>
                            <input asp-for="CityName" class="form-control bg-lightblue text-black" required>
                            <span asp-validation-for="CityName" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ImageFile" class="text-black">Upload Image:</label>
                            <div class="input-group">
                                <input asp-for="ImageFile" class="form-control-file bg-lightblue text-black">
                            </div>
                            <span asp-validation-for="ImageFile" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="text-black">Address:</label>
                            <textarea asp-for="Address" class="form-control bg-lightblue text-black" rows="3" required></textarea>
                            <span asp-validation-for="Address" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="text-black">Description:</label>
                            <textarea asp-for="Description" class="form-control bg-lightblue text-black" rows="3" required></textarea>
                            <span asp-validation-for="Description" class="small text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="OverallScore" class="text-black">Overall Score (1-5):</label>
                            <input asp-for="OverallScore" class="form-control bg-lightblue text-black" type="number" min="1" max="5" required>
                            <span asp-validation-for="OverallScore" class="small text-danger"></span>
                        </div>

                        <!-- Hidden input fields for cityId and restaurantId -->
                        <input type="hidden" name="cityId" value="@ViewData["cityId"]" />
                        <input type="hidden" name="restaurantId" value="@Model.Id" />
                        <hr/>
                        <button type="submit" class="ml-2 btn btn-warning">Edit Restaurant</button>

                        <!-- Go back -->
                        <hr>
                        <a href="javascript:history.go(-1)" class="btn card-header bg-secondary text-white border">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml" />
}